/**
 * Bundle KaTeX CSS with WOFF2 fonts inlined as base64 data URIs.
 *
 * Why: the PDF render path uses `page.setContent(html)` which has no stable
 * origin, so font URLs like `/fonts/KaTeX_*.woff2` won't resolve in Puppeteer.
 * Inlining the fonts produces a single self-contained CSS string that works
 * identically in the live preview and the headless-Chromium PDF render.
 *
 * Output: src/lib/katex-css.ts (committed to git; regenerated on every build).
 */

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(process.cwd());
const KATEX_CSS_PATH = path.join(ROOT, "node_modules/katex/dist/katex.min.css");
const FONT_DIR = path.join(ROOT, "node_modules/katex/dist/fonts");
const OUT_PATH = path.join(ROOT, "src/lib/katex-css.ts");

function loadFontAsDataUri(filename: string): string {
  const full = path.join(FONT_DIR, filename);
  const buf = fs.readFileSync(full);
  return `data:font/woff2;base64,${buf.toString("base64")}`;
}

function inlineFonts(css: string): { css: string; replaced: number } {
  let replaced = 0;

  // Each @font-face has src: url(fonts/X.woff2) format("woff2"),
  // url(fonts/X.woff) format("woff"), url(fonts/X.ttf) format("truetype")
  //
  // Strategy: find each woff2 reference, replace the *entire* src declaration
  // with a single inlined woff2 entry. We drop the woff/ttf fallbacks since
  // every Chromium we render in supports woff2.
  const updated = css.replace(
    /src:url\(fonts\/(KaTeX_[A-Za-z0-9_-]+\.woff2)\) format\("woff2"\)(?:,url\(fonts\/[^)]+\) format\("[^"]+"\))*/g,
    (_match, fontFile: string) => {
      const dataUri = loadFontAsDataUri(fontFile);
      replaced += 1;
      return `src:url(${dataUri}) format("woff2")`;
    },
  );

  return { css: updated, replaced };
}

function main() {
  if (!fs.existsSync(KATEX_CSS_PATH)) {
    console.error(
      `katex.min.css not found at ${KATEX_CSS_PATH}. Did you run pnpm install?`,
    );
    process.exit(1);
  }

  const raw = fs.readFileSync(KATEX_CSS_PATH, "utf8");
  const rawSize = Buffer.byteLength(raw, "utf8");

  const { css, replaced } = inlineFonts(raw);

  // Sanity check: every @font-face we expected to touch should have been hit.
  const fontFaceCount = (raw.match(/@font-face/g) ?? []).length;
  if (replaced !== fontFaceCount) {
    console.warn(
      `Warning: expected to inline ${fontFaceCount} fonts, inlined ${replaced}. ` +
        `Some @font-face entries were not matched — KaTeX may have changed its CSS shape.`,
    );
  }

  // Confirm no unresolved font URLs remain (anything still pointing at fonts/).
  if (/url\(fonts\//.test(css)) {
    console.error(
      "Refusing to write: leftover `url(fonts/...)` references in the CSS. " +
        "These would 404 in the Puppeteer PDF render path.",
    );
    process.exit(1);
  }

  // Escape the CSS for safe embedding in a TS template literal.
  const escaped = css.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");

  const banner = `// AUTO-GENERATED by scripts/bundle-katex-css.ts — do not edit by hand.
// Source: katex@${getKatexVersion()} (${path.basename(KATEX_CSS_PATH)})
// WOFF2 fonts inlined as base64 data URIs so this CSS is self-contained
// (works in Puppeteer's setContent path which has no stable origin).
// Regenerate with: pnpm bundle:katex
`;

  const out = `${banner}\nexport const katexCss = \`${escaped}\`;\n`;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, out, "utf8");

  const outSize = Buffer.byteLength(out, "utf8");
  console.log(
    `✓ Wrote ${OUT_PATH}\n` +
      `  CSS in:  ${(rawSize / 1024).toFixed(1)} KB\n` +
      `  CSS out: ${(outSize / 1024).toFixed(1)} KB (${replaced} fonts inlined)`,
  );
}

function getKatexVersion(): string {
  try {
    const pkg = JSON.parse(
      fs.readFileSync(
        path.join(ROOT, "node_modules/katex/package.json"),
        "utf8",
      ),
    ) as { version?: string };
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
}

main();
